name: Run Website Scraper

on:
  # Run on a schedule (this example runs every Monday at 00:00 UTC)
  schedule:
    - cron: '0 6 * * *'
  # Allows you to manually trigger the workflow if needed
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      DB_PATH: "data/db"
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          python -m playwright install # print environment variables

      - name: Run scraper script
        run: python src/innogrants_scrape.py

      - name: Run parser script
        run: python src/innogrants_parse.py

      - name: Commit changes if database updated
        run: |
          # Check for changes
          git config user.email "carloshurtadocomin@gmail.com"
          git config user.name "Carlos Hurtado"

          if [ -n "$(git status --porcelain $DB_PATH)" ]; then
            git add $DB_PATH
            git commit -m "Update database $(date)"
            git push
          else
            echo "No database changes detected."
          fi